(lang dune 3.20)

(name inference)

(generate_opam_files true)

(using menhir 3.0)

(package
 (name inference)
 (depends (ocaml (>= 5.0)) core core_unix dune ppx_inline_test)
 (tags
  ("substructural logic inference")))